# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:22
    depends_on:
      - postgresql
    ports:
      - "8024:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ../config/themes/cedar-03:/opt/bitnami/keycloak/themes/cedar-03
      - ../config/keycloak-realm.CEDAR.development.2023-07-05.json:/config/my-realm-config.json
      - ./scripts/my-entry-point.sh:/config/my-entry-point.sh
    entrypoint: ["/config/my-entry-point.sh"]
    command: /opt/bitnami/keycloak/bin/kc.sh start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
#    entrypoint: [ "/opt/bitnami/keycloak/bin/kc.sh", "start-dev",
#      # deactivate theme caching during theme development
#                  "--spi-theme-static-max-age=-1",
#                  "--spi-theme-cache-themes=false",
#                  "--spi-theme-cache-templates=false"
#      # ...
#    ]


volumes:
  postgresql_data:
    driver: local

